--- 
title: "資料科學與R語言"
author: "曾意儒 Yi-Ju Tseng"
date: "`r Sys.Date()`"
knit: "bookdown::render_book"
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
colorlinks: yes
lot: yes
lof: yes
download: no
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    config:
      fontsettings:
        family: Microsoft JhengHei
      download: null
documentclass: book
github-repo: yijutseng/DataAnalyticsWithRBook
description: "介紹如何使用R語言完成資料讀取、處理、分析與呈現，以及大數據技術與R的整合"
url: 'http\://yijutseng.github.io/DataScienceRBook'


---
```{r setup, include=FALSE}
options(
  htmltools.dir.version = FALSE, formatR.indent = 2, width = 80, digits = 2
)

pkg<-c('ggplot2', 'dplyr','lubridate','bit64','bookdown','knitr','rmarkdown','RCurl','data.table','stringr','reshape2','SportsAnalytics','readr','readxl','httr','jsonlite','XML','Rfacebook','rvest','rgdal','rgeos','maptools','ggmap','choroplethr','choroplethrMaps','WDI','treemapify','shiny','plotly','ggvis','googleVis','rpart',
        'rpart.plot','fields','arules','datasets','arulesViz','MASS',
       'caret','purrr','treemap','curl','xml2','tidyr')
ipak <- function(pkg){
    new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
    if (length(new.pkg)) 
        install.packages(new.pkg, dependencies = TRUE)
    sapply(pkg, require, character.only = TRUE)
}

ipak(pkg)
```

# {- #preface}
本書介紹如何使用[R語言](http://www.r-project.org/){target="_blank"}完成資料讀取 (檔案、透過API擷取或爬蟲)、資料清洗與處理、探索式資料分析、資料視覺化、互動式資料呈現 (搭配Shiny) 與資料探勘等，並介紹R與Hadoop Ecosystems介接方法。

資料探勘章節尚未完成，epub版本格式微調中。

如要一次安裝所有本書會使用到的套件，可在R內執行以下程式碼：
```{r eval=F}
install.packages("devtools")
devtools::install_github("yijutseng/DataAnalyticsWithRBook")
```

本書為[長庚大學資訊管理學系](http://im.cgu.edu.tw/bin/home.php){target="_blank"} [大數據分析方法](https://github.com/yijutseng/BigDataCGUIM){target="_blank"}課程教學使用書籍，並可搭配[YouTube平台上的教學影片](https://www.youtube.com/channel/UC2ZZMRLibtq2fD-la4YV_nA){target="_blank"}參考使用，**影片閱讀清單**詳見本書最末章節Ch \@ref(video) 教學影片資訊。

如果您想修改文字或範例，歡迎透過[此連結](https://goo.gl/forms/5Htobvwy2vsB7yiF3){target="_blank"}或是透過[GitHub](https://github.com/yijutseng/DataAnalyticsWithRBook/issues){target="_blank"} issue提供建議與回饋。


本書程式碼執行環境：
```{r}
sessionInfo()
```

本書使用套件版本：
```{r}
pkgInfo<-lapply(pkg, packageDescription, fields = c("Package", "Version"))
knitr::kable(data.frame(Package=sapply(pkgInfo, `[[`, 1),
  Version=sapply(pkgInfo, `[[`, 2)))
```

本著作係採用創用 CC 姓名標示-非商業性-禁止改作 3.0 台灣 授權條款授權。

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), pkg
), 'packages.bib')
```
